### ISSUE TITLE
Update Mod to 1.20+

### ISSUE THREAD

**Issue by ItsukaHiro** [vin350/AutoAttack#11]
Atleast, plz update the library. I did a little change in fabric.mod file and it work, but can't configure (it seem work well when using seperate library mod - the update version)

**Comment by Agentew04** [comment]
Hello, a pull request with the update to 1.20.1 version is in #15. Just wait for a merge and a release build.

**Comment by Agentew04** [comment]
Mod updated to 1.20.1, finally
