### ISSUE TITLE
when will it update to 1.20?

### ISSUE THREAD

**Issue by prostopareny** [vin350/AutoAttack#12]
when will it update to 1.20?

**Comment by Agentew04** [comment]
Hello!

I think I can try to update the mod later, do you need the 1.20 or 1.20.1 version?

**Comment by prostopareny** [comment]
1.20.1 version

**Comment by baesik** [comment]
Would love to see any update to the latest (1.20.1) version as well.

**Comment by Vexirio** [comment]
plsss 1.20.1 versioonn

**Comment by Agentew04** [comment]
Hello, a pull request with the update to 1.20.1 version is in #15. Just wait for a merge and a release build.

**Comment by Agentew04** [comment]
Mod updated to 1.20.1
