### ISSUE TITLE
[Feature Request] Toggle/Hold keybind to disable auto ranged attacks

### ISSUE THREAD

**Issue by Abicce** [vin350/AutoAttack#14]
Auto ranged attacks can be useful in a pinch, but in other times where aiming is necessary, these auto attacks could seriously backfire. I think it'd be useful to have a keybind that players can use to toggle between auto and manual ranged attacks or hold down to enable one or the other. I'd greatly appreciate it if you can consider this!

**Comment by Agentew04** [comment]
Hello, thanks for the feedback! I will try to implement it this week probably. I'll let you know here if it is finished.

**Comment by Abicce** [comment]
hi, thanks so much for taking my suggestion into consideration! I can’t wait for the next update! By the way, is there any chance that it’ll be compatible with Fabric 1.19.2?
