### ISSUE TITLE
Mod cannot start

### ISSUE THREAD

**Issue by EtherealAirRhyme** [vin350/AutoAttack#17]
Sorry to bother you, I encountered some issues with Autoattach after installing it. Every time I start the game, there is a high probability of it crashing. I don't know why, but occasionally it can be successfully launched.
I also encountered this issue when trying to remove other Mods and only installing autoattach. I don't know how to solve it
This is the crash log provided by the initiator. Can you tell me how to solve it? Thank you.
[错误报告-2023-9-8_19.21.28.zip](https://github.com/vin350/AutoAttack/files/12559039/-2023-9-8_19.21.28.zip)
Thank you very much and your Mod,The translator may not be accurate, please forgive me

**Comment by Agentew04** [comment]
Hello! 

I looked into the logs you provided and the problem probably is a bug when you are with no/slow internet. Hopefully today I can fix and update the mod. I will close this issue when a new version comes out.

Cheers

**Comment by EtherealAirRhyme** [comment]
> Hello!
> 
> I looked into the logs you provided and the problem probably is a bug when you are with no/slow internet. Hopefully today I can fix and update the mod. I will close this issue when a new version comes out.
> 
> Cheers

Hi, thank you very much for taking the time!
Cheers
