### ISSUE TITLE
1.20.4 Update

### ISSUE THREAD

**Issue by ghost** [vin350/AutoAttack#20]
Amazing mod !

**Comment by Agentew04** [comment]
Hello, thanks for the feedback! It is greatly appreciated. 😁

The mod has been updated to version 1.3.7 (Minecraft 1.20.4). You can find download links in the [modrinth page](https://modrinth.com/mod/autoattack/version/mc1.20.4-v1.3.7) or in the [releases](https://github.com/vin350/AutoAttack/releases/tag/v1.3.7) page.
