### ISSUE TITLE
1.21 update 

### ISSUE THREAD

**Issue by sebcioxd** [vin350/AutoAttack#30]
Please, this is essential mod for me

**Comment by N0K0** [comment]
Works just fine on 1.21 for me?

**Comment by sebcioxd** [comment]
it says that it isn't compatible with 1.21 for me.

**Comment by sebcioxd** [comment]
For me it say's that it isn't compatible with 1.21. Just fabric throws an error.
Also tried compiling it myself for 1.21 and it crashes after holding left mouse button.

Never mind - after compiling it, it actually works.

**Comment by JotaXLII** [comment]
Any tips on how to make it work in 1.21.1?
I seem to not be able to use it
