### ISSUE TITLE
Feature request: toggle key option for afk farm use

### ISSUE THREAD

**Issue by rutgerrrrr** [vin350/AutoAttack#4]
It would be extremely useful if there was an option to toggle auto attack with a keyboard key so that it could be used for afk'ing farms that would otherwise require the player to manually kill mobs.

**Comment by vin350** [comment]
would you like to press a key and the player is automatically attacking mobs?

then when you press it again it stops attacking

**Comment by rutgerrrrr** [comment]
> would you like to press a key and the player is automatically attacking mobs?
> 
> then when you press it again it stops attacking

Essentially yes but I wouldn't want it to be a kill aura either

**Comment by vin350** [comment]
don't worry! hahahaha

**Comment by vin350** [comment]
new mod version as released with this options
