### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by asdzxc233** [vin350/AutoAttack#5]
[crash-2022-12-12_04.51.04-client.txt](https://github.com/vin350/AutoAttack/files/10213442/crash-2022-12-12_04.51.04-client.txt)

**Comment by vin350** [comment]
are you trying to start on a server?

**Comment by asdzxc233** [comment]
> 您是否正在尝试在服务器上启动？

no,its always crashes at game start.

**Comment by asdzxc233** [comment]
> are you trying to start on a server?

no,its always crashes at game start.

**Comment by asdzxc233** [comment]
> are you trying to start on a server?

I tried not start on a server, its not crash, but when i start on a server again,its not crash too.

**Comment by vin350** [comment]
> I tried not start on a server, its not crash, but when i start on a server again,its not crash too.

the mod is client-side only, you must not put it on the server

**Comment by asdzxc233** [comment]
> > I tried not start on a server, its not crash, but when i start on a server again,its not crash too.
> 
> the mod is client-side only, you must not put it on the server

now its crash on my client

**Comment by asdzxc233** [comment]
> > > I tried not start on a server, its not crash, but when i start on a server again,its not crash too.
> > 
> > 
> > the mod is client-side only, you must not put it on the server
> 
> now its crash on my client

Sometimes it crashes, sometimes it doesn't.
